import express from "express";
const router = express.Router();
import userRouter from "./userRouter";
import productsRouter from "./productsRouter";
import toggleFavoriteRouter from "./toggleFavoriteRouter";
// import cartRouter from "./cartRouter";
import ordersRouter from "./ordersRouter";
// import adminPanelRouter from "./adminPanelRouter";
router.use("/user", userRouter);
router.use("/product", productsRouter);
router.use("/favorite", toggleFavoriteRouter);
// router.use("/cart", cartRouter);
router.use("/orders", ordersRouter);
// router.use("/admin", adminPanelRouter);
export default router;
