import express from "express";
const router = express.Router();
import userRouter from "./userRouter.js";
import productsRouter from "./productsRouter.js";
import toggleFavoriteRouter from "./toggleFavoriteRouter.js";
import cartRouter from "./cartRouter.js";
import ordersRouter from "./ordersRouter.js";
router.use("/user", userRouter);
router.use("/product", productsRouter);
router.use("/favorite", toggleFavoriteRouter);
router.use("/cart", cartRouter);
router.use("/orders", ordersRouter);
export default router;
